FROM golang:1.25.6-alpine

RUN apk add --no-cache ca-certificates
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

WORKDIR /app

COPY migrations ./migrations

ENTRYPOINT ["goose", "-dir", "/app/migrations"]
